### ISSUE TITLE
Realtime Voice Cloning Hakkında

### ISSUE THREAD

**Issue by mehmetgur** [AyseEe501/KMeans_Musteri_Segmentasyonu#1]
merhabalar, affınıza sığınarak konu dışı bir durum hakkında bilgi alacaktım. 
https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/770 
adresinde açtığınız issue'da türkçe dataset ile egitim yaptığınızı söylemişsiniz, acaba projenizde geldiğiniz son durum hakkında bilgi alabilir miyim? Ben de ses klonlama için türkçe veriseti arayışındayım da, eğittiğiniz veriyi paylaşabilme durumunuz var mıdır acaba?

**Comment by AyseEe501** [comment]
> 

Öncelikle merhaba;

Evet voice cloning ile Türkçe TTS' i oradaki yorumlarda konuştuğumuz Ekin, Common Voice veri seti  ile 50k da gerçekleştirdi. Dikkat katmanının 50k da bulunduğunu onun sayesinde öğrenmiş oldum. Ben 30k da kendi yaptığım veri setimle bir süreliğine bırakmak zorunda kaldım. Çünkü gpu belleğim yetersiz olduğundan, cpu da eğitimi sağladığım için daha fazla zaman alıyordu ve belleğimde yer bırakmıyordu. Bununla birlikte arka planda birden fazla projeyle uğraşmam da cabası. Bu sebeplerden dolayı durdurdum eğitimi ama veri setini tekrar arttırıp yeniden devam edeceğim birkaç gün içinde. Bunun dışında Ekin, elindekini çalıştırdı. Çok iyi olmasada Türkçe TTS  anlaşılır bir şekilde çalışıyor. Eğer veri seti daha iyi ve fazla olursa çok daha iyi bir sonuç çıkacağından ikimizde eminiz. Veri setimi elbette paylaşırım ancak biraz daha ekleme yaptıktan sonra paylaşsam daha iyi olur. Ama bununla denemek istiyorum derseniz yine size e-posta ile gönderebilirim :)

**Comment by mehmetgur** [comment]
merhabalar tekrar, geç dönüş yaptığım için kusura bakmayın :) peki eğittiğiniz türkçe modeli voice cloning de deneme şansınız oldu mu?

**Comment by AyseEe501** [comment]
> merhabalar tekrar, geç dönüş yaptığım için kusura bakmayın :) peki eğittiğiniz türkçe modeli voice cloning de deneme şansınız oldu mu?

Kusurluk bir sey yok, öyle düşünmeyin lütfen.Elbette denedim ama dikkat katmanını bulmak bu noktada çok onemli.Ben henüz 30k ile buna ulaşamadıģım için yeni bir dil varmış gibi bir sonuçla karşılaştım.Diğer arkadaşın eğittiği ise çalışıyor voice clonning içinde.Yani denemeden bir sonuç elde edemezdik zaten😅

**Comment by mehmetgur** [comment]
teşekkürler. peki diğer arkadaşın eğittiği modeli paylaşma şansınız var mı? ben de o model ile google colab üzerinden eğitim denemeleri yapabilirim. TTS vs benzeri alanlarda pek tecrübem yok ama genel olarak derin öğrenme alanında dilerseniz size yardımcı olmaya çalışabilirim

**Comment by AyseEe501** [comment]
Bana egittigi modelin ses kaydını atmıştı. .pt uzantılı dosyayı henüz atmadı.Common voice içindeki seslerin yenilendigini söyledi.Onlarla tekrar bir eģitim alıp benimle paylaşacaktı.O atmadan umarım bende iyi bir model eğitirim.Bununla birlikte ben daha önce TensorflowTTS icerisinde, Almanca TTS yapmış olan Yusuf Bey ile de görüşmüstüm.Bana Türkçe veri setinin olmamasından dolayı bunu yapmanın zaman alacaģını söylemişti.Yani TTS için en önemli kaynağımız veri seti bulmak oluyor kısacası.Bu arada deep learning dediniz ya nasıl mutlu oldum anlatamam :) Yani bunun için ayrıca teşekkür ederim:)
Böyle bilgisi olan kisilerle paylaşim yapmak inanılmaz guzel bir duygu.

Android için Outlook<https://aka.ms/AAb9ysg>’u edinin
________________________________

**Comment by mehmetgur** [comment]
Anladım, araştırdığım kadarıyla dediğiniz gibi en büyük problem Türkçe veri seti eksikliği. Umarım siz de eğitim kısmında sıkıntıları çözersiniz. ki belirli bir aşamaya geldiyseniz gerisi gelir artık

**Comment by AyseEe501** [comment]
Eğer o arkadaş atarsa size gönderirim tabi yine isterseniz.Ayrıca elimdeki veri setini isterseniz atabilirim de .Ama muhtemelen az gelecektir.Eğer klonu çalıştırmak istiyorsanız yardımcı da olurum elbette.Bastan bir traine başlayacağım ve kendimce daha iyi bir türkçe veri seti oluşturacağım.Eğer isterseniz onu da seve seve paylaşırım.Maksat insanlara bir faydamız dokunsun:)

Android için Outlook<https://aka.ms/AAb9ysg>’u edinin
________________________________

**Comment by mehmetgur** [comment]
çok teşekkürler, açıkçası çok memnun olurum :) hatta upload işi çok sıkıntı olmayacaksa sizin modelinizi de test etmek çok iyi olurdu aslında. mail adresimi vereyim isterseniz: gur-mehmet@hotmail.com
